### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by ivangretsky** [teppokoivula/pw-mvc#1]
Good day, @teppokoivula!

I have read through the readme and examined the code, but it is still not quite clear to me how it should work "in the real world".  Is it possible to see a more complete working example of this output approach? Sorry for a request instead of a real issue)

**Comment by teppokoivula** [comment]
Hi there, @ivangretsky!

I've been meaning to add a site profile based on this approach, just haven't had the time. Technically all the the basic stuff should already be explained in the README, but a site profile would definitely make things easier to grasp.

I'll leave this issue open as a reminder and try to get back to this as soon as possible. In the meantime if you have any specific questions, please let me know :)

**Comment by teppokoivula** [comment]
I'm closing this issue, since I'm currently in the process of rebuilding pw-mvc pretty much from the scratch, and this version probably won't get much attention anymore.

**Comment by ivangretsky** [comment]
Ok)
Where to follow the new pw-mvc development? Is it here or in some new repo?

**Comment by teppokoivula** [comment]
@ivangretsky, sorry for the delayed answer. I will open a new discussion forum thread, and probably add an update to this repository, as soon as I'm ready to publicly share the new version.

The version in question is actually almost ready to be released (as a beta version at least), but I'm hoping to complete a small site project using it first, and then duplicate that as a general purpose site profile – that's been taking longer than I had hoped, but it's exactly what was missing from pw-mvc :)

Anyway, I'll post an update on that as soon as possible!
